#####################################
# name: Makefile
# author: Dylan Morris <dhmorris@princeton.edu>
#
# Makefile to generate analyses
# for Stoddard et al 2019 study
# of hummingbird non-spectral color
# perception
#
####################################

#####################################
# Directory structure
####################################

default: all

SRC := src
OUT := out
DAT := dat

MCMC_CHAINS := $(OUT)/mcmc_chains
CLEANED_DATA_DIR := $(DAT)/cleaned
PLOT_PATH = $(OUT)/figures

#####################################
# File extensions and the like
####################################
CHAINS_SUFFIX = _chains.Rds

#####################################
# Expected bash settings
#
# Check these vs your local
# machine setup if you are having
# difficulty reproducing the
# analysis
#####################################

CXX := g++-8
MKDIR := @mkdir -p
RM := rm -rf

R_OPTIONS = --vanilla
R_COMMAND := Rscript $(R_OPTIONS)


#####################################
# Installation / dependencies
#
# Rules for prepping analysis
#####################################

.PHONY: depend

depend:
	$(R_COMMAND) $(SRC)/install_needed_packages.R


#####################################
# Analysis locations
#
# setup for data processing and
# model fitting
#####################################
# script locations
####################
MODEL_FITTING_SCRIPT = $(SRC)/fit_stan_model.R
DIAGNOSTIC_SCRIPT = $(SRC)/chain_diagnostics.R
REPORTED_QUANTITIES_SCRIPT = $(SRC)/extract_reported_quantities.R

####################
# data locations
####################

CLEANED_DATA = $(CLEANED_DATA_DIR)/CleanedDataTable.csv

#########################
# model names, model output locations
#########################

MAIN_MODEL_NAME = main_stan_model
MULTILEVEL_MODEL_NAME = multilevel_model
NO_ERROR_MODEL_NAME = no_error_model

MODELS = $(MAIN_MODEL_NAME) $(MULTILEVEL_MODEL_NAME) \
  $(NO_ERROR_MODEL_NAME) 

MODEL_DATA = $(CLEANED_DATA)

CHAINS = $(addsuffix $(CHAINS_SUFFIX), \
   $(addprefix $(MCMC_CHAINS)/, $(MODELS))) 

DIAGNOSTIC_FILE = $(OUT)/chain_diagnostics.csv
REPORTED_QUANTITIES_FILE = $(OUT)/reported_quantities.csv


##################################
# figure names and output paths
##################################
RIDGELINE_FIGS = $(addsuffix _ridgeline.pdf, \
   $(addprefix figure_, $(MODELS)))

FIGURES = figure_position_effect.pdf figure_experience.pdf \
   figure_pp_check.pdf figure_pp_check_all.pdf\
   figure_axis_difference.pdf \
   figure_axis_difference_multilevel.pdf \
   $(RIDGELINE_FIGS)

FIGURE_PATHS := $(addprefix $(PLOT_PATH)/, $(FIGURES))


#############################
# Rules
#
# definition of dependency
# tree and specification of
# rules for doing stuff
#############################


####################
# rules for model fitting and post-processing
####################

# generic recipe for model chains output
$(MCMC_CHAINS)/%$(CHAINS_SUFFIX): $(SRC)/%.stan $(MODEL_FITTING_SCRIPT) $(MODEL_DATA)
	$(MKDIR) $(MCMC_CHAINS)
	$(R_COMMAND) $(MODEL_FITTING_SCRIPT) $< $(MODEL_DATA) $@

.PHONY: chains
chains: $(CHAINS)

$(DIAGNOSTIC_FILE): $(DIAGNOSTIC_SCRIPT) $(CHAINS) $(CLEANED_DATA)
	$(MKDIR) $(MCMC_CHAINS)
	$(R_COMMAND) $^ $@

$(REPORTED_QUANTITIES_FILE): $(REPORTED_QUANTITIES_SCRIPT) \
   $(MCMC_CHAINS)/$(MAIN_MODEL_NAME)$(CHAINS_SUFFIX) \
   $(CLEANED_DATA)
	$(R_COMMAND) $^ $@

####################
# Figures
#
# Rules for autogenerating
# manuscript figures
#
####################

#################
# Generic fig rule
#
# generically, figures generated by file with same name, unless
# otherwise specified

$(PLOT_PATH)/%.pdf: $(SRC)/%.R $(MCMC_CHAINS)/$(MAIN_MODEL_NAME)$(CHAINS_SUFFIX) $(CLEANED_DATA)
	$(MKDIR) $(PLOT_PATH)
	$(R_COMMAND) $^ $@
	@$(RM) Rplots.pdf

#################
# other fig rules
#################
$(PLOT_PATH)/figure_%_ridgeline.pdf: $(SRC)/figure_posterior_ridgeline.R \
   $(MCMC_CHAINS)/%$(CHAINS_SUFFIX) $(CLEANED_DATA)
	$(MKDIR) $(PLOT_PATH)
	$(R_COMMAND) $^ $@
	@$(RM) Rplots.pdf


$(PLOT_PATH)/figure_axis_difference_multilevel.pdf: $(SRC)/figure_axis_difference.R $(MCMC_CHAINS)/$(MULTILEVEL_MODEL_NAME)$(CHAINS_SUFFIX) $(CLEANED_DATA)
	@$(MKDIR) $(PLOT_PATH)
	$(R_COMMAND) $^ $@
	@$(RM) Rplots.pdf


$(PLOT_PATH)/figure_pp_check_all.pdf: $(SRC)/figure_pp_check.R $(CHAINS) $(CLEANED_DATA) $(CLEANED_DATA_FULL)
	@$(MKDIR) $(PLOT_PATH)
	$(R_COMMAND) $^ $@
	@$(RM) Rplots.pdf

.PHONY: figs
figs: $(FIGURE_PATHS)

#####################################
# Cleanup
#
# Rules for cleaning up
# directories
#####################################

.PHONY: clean del-temp

del-temp:
	@$(RM) *#*
	@$(RM) *~
	@$(RM) */*~
	@$(RM) */*#

clean: del-temp
	@$(RM) out
	@$(RM) .Rhistory
	@$(RM) Rplots.pdf


#####################################
# Global rules
#
# define any rules that derive
# from everything above
#####################################

.PHONY: all
all: depend $(CLEANED_DATA) \
   $(CHAINS) $(DIAGNOSTIC_FILE) \
   $(REPORTED_QUANTITIES_FILE) $(FIGURE_PATHS)
